### ISSUE TITLE
Issue with error 50 when installing mod_aspnet

### ISSUE THREAD

**Issue by wingZero21** [chef-cookbooks/iis#285]
### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
12.10.24

### Platform Details
Windows Server 2012

### Scenario:
Attempting to install .net 35 pre-requisites

### Steps to Reproduce:
Running recipe iis::mod_aspnet

### Expected Result:
When running I am getting the below errors.
```
==> default: [2016-06-28T01:06:44-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_feature[NetFx3] (iis::mod_aspnet line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127, 3010], but received '50'
==> default: ---- Begin output of C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart   ----
==> default: STDOUT: Deployment Image Servicing and Management tool
==> default:
==> default: Version: 6.3.9600.17031
==> default:
==> default:
==> default:
==> default: Image Version: 6.3.9600.17031
==> default:
==> default:
==> default:
==> default: Enabling feature(s)
==> default:
==> default:
==> default:
==> default: Error: 50
==> default:
==> default:
==> default:
==> default: The operation is complete but NetFx3 feature was not enabled.
==> default:
==> default: A required parent feature may not be enabled. You can use the /enable-feature /all option to automatically enable each parent feature from the following list. If the parent feature(s) are already enabled, refer to the log file for further diagnostics.
==> default:
==> default: NetFx3ServerFeatures
==> default:
==> default: The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
==> default: STDERR:
==> default: ---- End output of C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart   ----
==> default: Ran C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart   returned 50
```

### Potential Fix

Amended the mod_aspnet recipe detailed below.

Details:
Original
```
include_recipe 'iis'
include_recipe 'iis::mod_isapi'

features = if Opscode::IIS::Helper.older_than_windows2008r2?
             %w(NET-Framework)
           else
             %w(IIS-NetFxExtensibility IIS-ASPNET)
           end

features.each do |feature|
  windows_feature feature do
    action :install
  end
end
```

Amendment
```
include_recipe 'iis'
include_recipe 'iis::mod_isapi'

features = if Opscode::IIS::Helper.older_than_windows2008r2?
             %w(NET-Framework)
           else
             %w(NetFx3 IIS-NetFxExtensibility IIS-ASPNET)
           end

features.each do |feature|
  windows_feature feature do
    action :install
    all true
  end
end
```

**Comment by wingZero21** [comment]
Added pull request to fix this - https://github.com/chef-cookbooks/iis/pull/286

**Comment by EasyAsABC123** [comment]
Resolved in #286

**Comment by joshoohaah** [comment]
FYI. this will still happen on 2012 and 2016 if the image has some Windows updates installed on it.  This hotfix (https://support.microsoft.com/en-us/help/3005628/update-for-the--net-framework-3-5-on-windows-8--windows-8-1--windows-s ) solves that problem and allows `Netfx3` to install so these other components can install.   I wonder if there is value in adding this check to the cookbook?

**Comment by EasyAsABC123** [comment]
We can definitely look into that

**Comment by spuder** [comment]
My workaround for this issue
Download hotfix and install it before installing .net 3.5


Note microsoft offers .exe and .msu hotfixes. The msu hotfix is best for machines that have had windows updates cleaned up with `DISM "/StartComponentCleanup" and "/ResetBase" `. This url is for the msu hotfix


```ruby
remote_file 'hotfix KB2966828' do
  path "#{Chef::Config[:file_cache_path]}/Windows8.1-KB2966828-x64.msu"
  source 'http://go.microsoft.com/fwlink/?linkid=517245&clcid=0x409' # Best to cache this on artifact repository incase microsoft ever changes url
  action :nothing
end

# Requires chef >=12.17
msu_package 'KB2966828' do
  source "#{Chef::Config[:file_cache_path]}/Windows8.1-KB2966828-x64.msu"
  checksum 'f8928bd61d6026343b03774427d3e945e51806576eb23c97a98d68434515c60d'
  action :nothing
  notifies :create, 'remote_file[hotfix KB2966828]', :before
end

windows_feature 'NetFx3' do
  action :install
  all true
  notifies :install, 'msu_package[KB2966828]', :before
end

windows_feature 'NetFx3ServerFeatures' do
  action :install
  all true
  notifies :install, 'msu_package[KB2966828]', :before
end
```
